# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [9]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [11]:
### [your code here]
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [27]:
### [your code here]
a = np.random.rand(2,3,5)
e = np.random.random((2,3,5))
x = np.random.randint(0,10,size=(2,3,5))


### 4. Print a.


In [26]:
### [your code here]
print(a)


[[[0.10368891 0.66152338 0.97035731 0.53611069 0.93287925]
  [0.2495735  0.71911841 0.31860878 0.45763689 0.9351855 ]
  [0.69769792 0.48297627 0.5898844  0.05982341 0.57220267]]

 [[0.45356623 0.9746517  0.58683604 0.41552222 0.99643   ]
  [0.51588622 0.37589974 0.9827187  0.80063359 0.09069563]
  [0.31070519 0.70989374 0.09155035 0.86769875 0.96234685]]]


 ### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [29]:
### [your code here]
b=np.ones((5,2,3))


### 6. Print b.


In [30]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [33]:
### [your code here]
if a.size == b.size:
    print('yes,their size are :',a.size)
else:
    print ('No, they have diferent size')

yes,their size are : 30



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
print(a.shape)
print(b.shape)

"""it is not possible because they dont have the same shape."""


(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [35]:
### [your code here]
c = b.transpose(1,2,0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [37]:
### [your code here]
d = a + c
print(d)

[[[1.47109166 1.87430533 1.96773855 1.99198382 1.40658446]
  [1.67023612 1.86118689 1.93350031 1.8246161  1.31522427]
  [1.43855414 1.1343747  1.61485169 1.91470795 1.26735135]]

 [[1.4936253  1.37988066 1.43244672 1.9917685  1.27706403]
  [1.23921167 1.1289231  1.68455068 1.44317315 1.91000306]
  [1.64451545 1.69744889 1.24251246 1.79674791 1.40340144]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [39]:
### [your code here]
print(a)

print(d)



[[[0.47109166 0.87430533 0.96773855 0.99198382 0.40658446]
  [0.67023612 0.86118689 0.93350031 0.8246161  0.31522427]
  [0.43855414 0.1343747  0.61485169 0.91470795 0.26735135]]

 [[0.4936253  0.37988066 0.43244672 0.9917685  0.27706403]
  [0.23921167 0.1289231  0.68455068 0.44317315 0.91000306]
  [0.64451545 0.69744889 0.24251246 0.79674791 0.40340144]]]
[[[1.47109166 1.87430533 1.96773855 1.99198382 1.40658446]
  [1.67023612 1.86118689 1.93350031 1.8246161  1.31522427]
  [1.43855414 1.1343747  1.61485169 1.91470795 1.26735135]]

 [[1.4936253  1.37988066 1.43244672 1.9917685  1.27706403]
  [1.23921167 1.1289231  1.68455068 1.44317315 1.91000306]
  [1.64451545 1.69744889 1.24251246 1.79674791 1.40340144]]]



### 12. Multiply a and c. Assign the result to e.


In [41]:
### [your code here]
e = a*c
print(e)

[[[0.47109166 0.87430533 0.96773855 0.99198382 0.40658446]
  [0.67023612 0.86118689 0.93350031 0.8246161  0.31522427]
  [0.43855414 0.1343747  0.61485169 0.91470795 0.26735135]]

 [[0.4936253  0.37988066 0.43244672 0.9917685  0.27706403]
  [0.23921167 0.1289231  0.68455068 0.44317315 0.91000306]
  [0.64451545 0.69744889 0.24251246 0.79674791 0.40340144]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
"""yes, because is like multiply by 1"""




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [44]:
### [your code here]

d_max =np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9919838199031488
1.1289230987046321
1.581719344199326



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [45]:
### [your code here]
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [46]:
### [your code here]
for i in range(d.shape[0]):
    for j in range (d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i,j,k]
            if val == d_min:
                f[i, j, k] = 0
            elif val == d_max:
                f[i, j, k] = 100
            elif val == d_mean:
                f[i, j, k] = 50
            elif d_min < val < d_mean:
                f[i, j, k] = 25
            elif d_mean < val < d_max:
                f[i, j, k] = 75
            





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [48]:
### [your code here]
print(d)
print(f)

[[[1.47109166 1.87430533 1.96773855 1.99198382 1.40658446]
  [1.67023612 1.86118689 1.93350031 1.8246161  1.31522427]
  [1.43855414 1.1343747  1.61485169 1.91470795 1.26735135]]

 [[1.4936253  1.37988066 1.43244672 1.9917685  1.27706403]
  [1.23921167 1.1289231  1.68455068 1.44317315 1.91000306]
  [1.64451545 1.69744889 1.24251246 1.79674791 1.40340144]]]
[[[ 25.  75.  75. 100.  25.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  75.  25.]
  [ 25.   0.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]


### 18.Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question. 

In [51]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                f[i, j, k] = "A"
            elif val == d_max:
                f[i, j, k] = "E"
            elif val == d_mean:
                f[i, j, k] = "C"
            elif d_min < val < d_mean:
                f[i, j, k] = "B"
            elif d_mean < val < d_max:
                f[i, j, k] = "D"

ValueError: could not convert string to float: 'B'